name: Production Builds

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        default: 'nightscout/AndroidAPS'
      ref:
        description: 'Ref / Branch'
        required: true
        default: 'master'
      keyStoreContent:
        description: 'Base64 encoded keystore file'
        required: true
      keyStorePassword:
        description: 'Keystore password'
        required: true
      keyPassword:
        description: 'Key password'
        required: true
      keyAlias:
        description: 'Key alias'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run Build Project
      - name: Build with Gradle
        run: ./gradlew app:assembleFullRelease

      # Setup build tool version variable
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      # Sign APK File
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/full/release
          signingKeyBase64: ${{ inputs.keyStoreContent }}
          keyStorePassword: ${{ inputs.keyStorePassword }}
          alias: ${{ inputs.keyAlias }}
          keyPassword: ${{ inputs.keyPassword }}
        env:
          # override default build-tools version (29.0.3) -- optional
          # BUILD_TOOLS_VERSION: "35.0.2"
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      # Upload Artifact Build
      - name: Upload Logfiles
        uses: actions/upload-artifact@v4
        with:
          name: 'App-Build-${{ github.run_number }}'
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          # path: app/build/outputs/apk/full/release/app-full-release-unsigned-signed.apk
          retention-days: 1
